# Generated by Django 5.0.2 on 2026-07-13 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
        ('users', '0002_alter_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='recommendations',
            field=models.ManyToManyField(to='shop.product'),
        ),
    ]
