services:
  db:
    image: postgis/postgis:15-3.4
    restart: always
    volumes:
      - database_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER}" ]
      interval: 5s
      timeout: 3s
      retries: 5
  api:
    build: .
    tty: true
    restart: always
    volumes:
      - .:/code
      - static:/static
      - media:/media
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    environment:
      POSTGRES_NAME: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      DJANGO_SECRET_KEY: ${DJANGO_SECRET_KEY}
      API_ALLOWED_HOSTS: ${API_ALLOWED_HOSTS}
      DJANGO_DEBUG: ${DJANGO_DEBUG}
      API_ENV: ${API_ENV}
volumes:
  static: {}
  media: {}
  database_data: {}
